# Copyright (c) 2020 Ryan Cross
# SPDX-License-Identifier: MIT

# Uncomment the following line to enable the Sofle OLED Display
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

# Uncomment these two lines to add support for encoders
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment this line below to add rgb underglow / backlight support
# CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
# CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n

# General Configuration
CONFIG_NICE_OLED_ON=y                             #	Enable nice oled widget compatibility
#CONFIG_NICE_EPAPER_ON=                           #	Enable nice view widget compatibility
#CONFIG_LV_Z_VDB_SIZE=                            # (OLED), 100 (ePaper)	Buffer size for LVGL
#CONFIG_LV_DPI_DEF=                               # (OLED), 161 (ePaper)	Dots per inch (DPI) setting
#CONFIG_LV_Z_BITS_PER_PIXEL=                      #	Bits per pixel
#CONFIG_LV_COLOR_DEPTH=                           #	Color depth
#CONFIG_ZMK_DISPLAY_WORK_QUEUE=                   #	Work queue type
#CONFIG_ZMK_DISPLAY_STATUS_SCREEN=                #	Status screen type
#CONFIG_ZMK_DISPLAY_BLANK_ON_IDLE=                # (OLED), y (ePaper)	Control display blanking on idle for nice_custom/nice_epaper
#CONFIG_LV_Z_MEM_POOL_SIZE=                       #	Memory pool size
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_STACK_SIZE=  # (3072 with RAW HID)	Display thread stack size
#CONFIG_ZMK_DISPLAY_DEDICATED_THREAD_PRIORITY=    #	Display thread priority (lower = higher priority)
#CONFIG_NICE_OLED_WIDGET_STATUS=                  #	Custom nice oled status widget (Selects LVGL features)
#CONFIG_NICE_OLED_WIDGET_INVERTED=                #	Invert display colors
#CONFIG_NICE_OLED_WIDGET_OUTPUT_BACKGROUND=       # (OLED), y (ePaper)	Enable output background on central and peripheral
#CONFIG_NICE_OLED_CUSTOM_CANVAS_WIDTH=            # (ePaper), 32 (OLED)	Custom Canvas Width overwriting default calculation
#CONFIG_NICE_OLED_CUSTOM_CANVAS_HEIGHT=           # (ePaper), 128 (OLED)	Custom Canvas Height overwriting default calculation

# Sleep & Animation (Central & Peripheral)
CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_IDLE=n
CONFIG_NICE_OLED_SHOW_SLEEP_ART_ON_SLEEP=n

# Peripheral Specific
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_WPM=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_HEAD=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_POKEMON=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SPACEMAN=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL_VIM=n
CONFIG_NICE_OLED_WIDGET_STATIC_IMAGE_PERIPHERAL_VIP_MARCOS=y

# Central Specific
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=n
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=y
CONFIG_NICE_OLED_WIDGET_RESPONSIVE_BONGO_CAT=n

# Raw HID
CONFIG_NICE_OLED_WIDGET_RAW_HID_VOLUME=n
CONFIG_NICE_OLED_WIDGET_RAW_HID_VOLUME_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_RAW_HID_VOLUME_CUSTOM_Y=98

# Modifiers Indicators
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_BOX=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_VER_ALIGN_CENTER=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_WINDOWS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_BONGO_CAT=n
